version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9090:9090"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command:
      - "server"
      - "/data"
      - "--console-address=:9090"
    networks:
      default:
        aliases:
          - minio.mlops-e2e
      mlops-e2e:
        aliases:
          - minio.mlops-e2e
  orchestrator:
      image: mlops-e2e-orchestrator
      build:
        context: ./src/orchestrator
        dockerfile: ./Dockerfile

volumes:
  minio_data: {}

networks:
  mlops-e2e:
