version: '3'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - src/config/.env
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    networks:
      - mlops_e2e


  prefect-database:
    image: postgres:15.2-alpine
    env_file:
      - src/config/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mlops_e2e

  prefect-api:
    image: prefecthq/prefect:2.11-python3.11
    volumes:
      - prefect_data:/root/.prefect
    ports:
      - "127.0.0.1:4200:4200"
    env_file:
      - src/config/.env
    depends_on:
      - prefect-database
    entrypoint: [ "/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    networks:
      - mlops_e2e

  prefect-agent:
    image: prefecthq/prefect:2.11-python3.11
    environment:
      - PREFECT_API_URL=http://prefect-api:4200/api
    depends_on:
      - prefect-api
    entrypoint: [ "/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "--work-queue", "mlops_e2e_cv" ]
    networks:
      - mlops_e2e


volumes:
  minio_data: {}
  prefect_data: {}
  postgres_data: {}

networks:
  mlops_e2e:
