version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9090:9090"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command:
      - "server"
      - "/data"
      - "--console-address=:9090"
    networks:
      default:
        aliases:
          - minio.mlops-end-to-end
      mlops-end-to-end:
        aliases:
          - minio.mlops-end-to-end

volumes:
  minio_data: {}

networks:
  mlops-end-to-end:
