version: '3'

services:
  ds_experiment:
    image: jupyter/base-notebook:latest
    container_name: ds_experiment
    ports:
      - "8888:8888"
    volumes:
      - "./src:/home/jovyan/src"

  minio:
    image: minio/minio:latest
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - src/.env
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]


  prefect-database:
    image: postgres:15.2-alpine
    env_file:
      - src/.env
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  prefect-api:
    image: prefecthq/prefect:2.11-python3.11
    volumes:
      - prefect:/root/.prefect
    ports:
      - "127.0.0.1:4200:4200"
    environment:
      - PREFECT_UI_URL=http://127.0.0.0:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@prefect-database:5432/prefect
    depends_on:
      - prefect-database
    entrypoint: [ "/opt/prefect/entrypoint.sh", "prefect", "server", "start"]

  prefect-agent:
    image: prefecthq/prefect:2.11-python3.11
    environment:
      - PREFECT_API_URL=http://prefect-api:4200/api
    depends_on:
      - prefect-api
    entrypoint: [ "/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "--work-queue", "mlops_e2e_cv" ]


volumes:
  minio_data: {}
  prefect: {}
  db: {}

networks:
  mlops_e2e:
