version: '3'

services:
  ds-experiment:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    volumes:
      - ./src:/home/jovyan/app/src
    env_file:
      - src/config/.env
    environment:
      - MINIO_HOST=minio
      - PREFECT_API_URL=http://prefect-api:4200/api
    ports:
      - "8888:8888"
    networks:
      - mlops_e2e

  minio:
    image: minio/minio:latest
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - src/config/.env
    entrypoint: [ "minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data" ]
    networks:
      - mlops_e2e


  zenml-database:
    image: mysql:8.2
    env_file:
      - src/config/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - mlops_e2e

  zenml-server:
    image: zenmldocker/zenml-server:latest
    ports:
      - "8080:8080"
    env_file:
      - src/config/.env
    depends_on:
      - zenml-database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mlops_e2e


volumes:
  minio_data: { }
  mysql_data: { }

networks:
  mlops_e2e:
